## Update BLS  Entry

ls /boot/loader/entries/
vi /boot/loader/entries/xxxxxxxx-xxxx.conf

title Red Hat Enterprise Linux
version 5.14.0-xxx
linux /vmlinuz-5.14.0-xxx
initrd /initramfs-5.14.0-xxx.img
options root=UUID=... ro rhgb quiet
grub_class rhel
grub_user admin
unrestricted

## Rebuild GRUB Configuration
grub2-mkconfig -o /boot/grub2/grub.cfg

Verify

grep superusers /boot/efi/EFI/redhat/grub.cfg
 Expected: set superusers="admin"

Reboot
Press “e” or “c” and you should be prompted for a username and password
Login

## Secure GRUB config permissions

chmod 600 /boot/efi/EFI/redhat/grub.cfg
chown root:root /boot/efi/EFI/redhat/grub.cfg
