## Update BLS  Entry

ls /boot/loader/entries/
vi /boot/loader/entries/xxxxxxxx-xxxx.conf

title Red Hat Enterprise Linux
version 5.14.0-xxx
linux /vmlinuz-5.14.0-xxx
initrd /initramfs-5.14.0-xxx.img
options root=UUID=... ro rhgb quiet
grub_class rhel
grub_user admin
unrestricted
